<?php

namespace Database\Seeders;

use App\Models\WhoBB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class whoBBSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['usia' => '0', 'jk' => 'l', 'mean_bb' => '3.3', 'std_dev' => '0.55', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '1', 'jk' => 'l', 'mean_bb' => '4.5', 'std_dev' => '0.65', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '2', 'jk' => 'l', 'mean_bb' => '5.6', 'std_dev' => '0.75', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '3', 'jk' => 'l', 'mean_bb' => '6.4', 'std_dev' => '0.8', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '4', 'jk' => 'l', 'mean_bb' => '7.0', 'std_dev' => '0.85', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '5', 'jk' => 'l', 'mean_bb' => '7.5', 'std_dev' => '0.9', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '6', 'jk' => 'l', 'mean_bb' => '7.9', 'std_dev' => '0.95', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '7', 'jk' => 'l', 'mean_bb' => '8.3', 'std_dev' => '1.0', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '8', 'jk' => 'l', 'mean_bb' => '8.6', 'std_dev' => '1.05', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '9', 'jk' => 'l', 'mean_bb' => '8.9', 'std_dev' => '1.05', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '10', 'jk' => 'l', 'mean_bb' => '9.2', 'std_dev' => '1.1', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '11', 'jk' => 'l', 'mean_bb' => '9.4', 'std_dev' => '1.15', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '12', 'jk' => 'l', 'mean_bb' => '9.6', 'std_dev' => '1.2', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '13', 'jk' => 'l', 'mean_bb' => '9.9', 'std_dev' => '1.2', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '14', 'jk' => 'l', 'mean_bb' => '10.1', 'std_dev' => '1.25', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '15', 'jk' => 'l', 'mean_bb' => '10.3', 'std_dev' => '1.25', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '16', 'jk' => 'l', 'mean_bb' => '10.5', 'std_dev' => '1.3', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '17', 'jk' => 'l', 'mean_bb' => '10.7', 'std_dev' => '1.35', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '18', 'jk' => 'l', 'mean_bb' => '10.9', 'std_dev' => '1.4', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '19', 'jk' => 'l', 'mean_bb' => '11.1', 'std_dev' => '1.4', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '20', 'jk' => 'l', 'mean_bb' => '11.3', 'std_dev' => '1.45', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '21', 'jk' => 'l', 'mean_bb' => '11.5', 'std_dev' => '1.5', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '22', 'jk' => 'l', 'mean_bb' => '11.8', 'std_dev' => '1.45', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '23', 'jk' => 'l', 'mean_bb' => '12.0', 'std_dev' => '1.5', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '24', 'jk' => 'l', 'mean_bb' => '12.2', 'std_dev' => '1.55', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '25', 'jk' => 'l', 'mean_bb' => '12.4', 'std_dev' => '1.55', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '26', 'jk' => 'l', 'mean_bb' => '12.5', 'std_dev' => '1.65', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '27', 'jk' => 'l', 'mean_bb' => '12.7', 'std_dev' => '1.7', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '28', 'jk' => 'l', 'mean_bb' => '12.9', 'std_dev' => '1.7', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '29', 'jk' => 'l', 'mean_bb' => '13.1', 'std_dev' => '1.75', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '30', 'jk' => 'l', 'mean_bb' => '13.3', 'std_dev' => '1.8', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '31', 'jk' => 'l', 'mean_bb' => '13.5', 'std_dev' => '1.8', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '32', 'jk' => 'l', 'mean_bb' => '13.7', 'std_dev' => '1.85', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '33', 'jk' => 'l', 'mean_bb' => '13.8', 'std_dev' => '1.9', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '34', 'jk' => 'l', 'mean_bb' => '14.0', 'std_dev' => '1.9', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '35', 'jk' => 'l', 'mean_bb' => '14.2', 'std_dev' => '1.95', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '36', 'jk' => 'l', 'mean_bb' => '14.3', 'std_dev' => '2.0', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '37', 'jk' => 'l', 'mean_bb' => '14.5', 'std_dev' => '2.05', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '38', 'jk' => 'l', 'mean_bb' => '14.7', 'std_dev' => '2.05', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '39', 'jk' => 'l', 'mean_bb' => '14.8', 'std_dev' => '2.1', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '40', 'jk' => 'l', 'mean_bb' => '15.0', 'std_dev' => '2.15', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '41', 'jk' => 'l', 'mean_bb' => '15.2', 'std_dev' => '2.15', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '42', 'jk' => 'l', 'mean_bb' => '15.3', 'std_dev' => '2.2', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '43', 'jk' => 'l', 'mean_bb' => '15.5', 'std_dev' => '2.25', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '44', 'jk' => 'l', 'mean_bb' => '15.7', 'std_dev' => '2.25', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '45', 'jk' => 'l', 'mean_bb' => '15.8', 'std_dev' => '2.35', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '46', 'jk' => 'l', 'mean_bb' => '16.0', 'std_dev' => '2.35', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '47', 'jk' => 'l', 'mean_bb' => '16.2', 'std_dev' => '2.35', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '48', 'jk' => 'l', 'mean_bb' => '16.3', 'std_dev' => '2.45', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '49', 'jk' => 'l', 'mean_bb' => '16.5', 'std_dev' => '2.45', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '50', 'jk' => 'l', 'mean_bb' => '16.7', 'std_dev' => '2.5', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '51', 'jk' => 'l', 'mean_bb' => '16.8', 'std_dev' => '2.55', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '52', 'jk' => 'l', 'mean_bb' => '17.0', 'std_dev' => '2.6', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '53', 'jk' => 'l', 'mean_bb' => '17.2', 'std_dev' => '2.6', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '54', 'jk' => 'l', 'mean_bb' => '17.3', 'std_dev' => '2.7', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '55', 'jk' => 'l', 'mean_bb' => '17.5', 'std_dev' => '2.7', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '56', 'jk' => 'l', 'mean_bb' => '17.7', 'std_dev' => '2.75', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '57', 'jk' => 'l', 'mean_bb' => '17.8', 'std_dev' => '2.8', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '58', 'jk' => 'l', 'mean_bb' => '18.0', 'std_dev' => '2.85', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '59', 'jk' => 'l', 'mean_bb' => '18.2', 'std_dev' => '2.85', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '60', 'jk' => 'l', 'mean_bb' => '18.3', 'std_dev' => '2.95', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '0', 'jk' => 'p', 'mean_bb' => '3.2', 'std_dev' => '0.5', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '1', 'jk' => 'p', 'mean_bb' => '4.2', 'std_dev' => '0.65', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '2', 'jk' => 'p', 'mean_bb' => '5.1', 'std_dev' => '0.75', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '3', 'jk' => 'p', 'mean_bb' => '5.8', 'std_dev' => '0.85', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '4', 'jk' => 'p', 'mean_bb' => '6.4', 'std_dev' => '0.9', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '5', 'jk' => 'p', 'mean_bb' => '6.9', 'std_dev' => '0.95', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '6', 'jk' => 'p', 'mean_bb' => '7.3', 'std_dev' => '1.0', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '7', 'jk' => 'p', 'mean_bb' => '7.6', 'std_dev' => '1.1', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '8', 'jk' => 'p', 'mean_bb' => '7.9', 'std_dev' => '1.15', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '9', 'jk' => 'p', 'mean_bb' => '8.2', 'std_dev' => '1.15', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '10', 'jk' => 'p', 'mean_bb' => '8.5', 'std_dev' => '1.2', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '11', 'jk' => 'p', 'mean_bb' => '8.7', 'std_dev' => '1.25', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '12', 'jk' => 'p', 'mean_bb' => '8.9', 'std_dev' => '1.3', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '13', 'jk' => 'p', 'mean_bb' => '9.2', 'std_dev' => '1.3', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '14', 'jk' => 'p', 'mean_bb' => '9.4', 'std_dev' => '1.35', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '15', 'jk' => 'p', 'mean_bb' => '9.6', 'std_dev' => '1.4', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '16', 'jk' => 'p', 'mean_bb' => '9.8', 'std_dev' => '1.4', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '17', 'jk' => 'p', 'mean_bb' => '10.0', 'std_dev' => '1.45', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '18', 'jk' => 'p', 'mean_bb' => '10.2', 'std_dev' => '1.5', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '19', 'jk' => 'p', 'mean_bb' => '10.4', 'std_dev' => '1.55', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '20', 'jk' => 'p', 'mean_bb' => '10.6', 'std_dev' => '1.55', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '21', 'jk' => 'p', 'mean_bb' => '10.9', 'std_dev' => '1.55', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '22', 'jk' => 'p', 'mean_bb' => '11.1', 'std_dev' => '1.6', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '23', 'jk' => 'p', 'mean_bb' => '11.3', 'std_dev' => '1.65', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '24', 'jk' => 'p', 'mean_bb' => '11.5', 'std_dev' => '1.65', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '25', 'jk' => 'p', 'mean_bb' => '11.7', 'std_dev' => '1.7', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '26', 'jk' => 'p', 'mean_bb' => '11.9', 'std_dev' => '1.75', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '27', 'jk' => 'p', 'mean_bb' => '12.1', 'std_dev' => '1.8', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '28', 'jk' => 'p', 'mean_bb' => '12.3', 'std_dev' => '1.85', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '29', 'jk' => 'p', 'mean_bb' => '12.5', 'std_dev' => '1.85', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '30', 'jk' => 'p', 'mean_bb' => '12.7', 'std_dev' => '1.9', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '31', 'jk' => 'p', 'mean_bb' => '12.9', 'std_dev' => '1.95', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '32', 'jk' => 'p', 'mean_bb' => '13.1', 'std_dev' => '2', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '33', 'jk' => 'p', 'mean_bb' => '13.3', 'std_dev' => '2', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '34', 'jk' => 'p', 'mean_bb' => '13.5', 'std_dev' => '2.05', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '35', 'jk' => 'p', 'mean_bb' => '13.7', 'std_dev' => '2.1', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '36', 'jk' => 'p', 'mean_bb' => '13.9', 'std_dev' => '2.1', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '37', 'jk' => 'p', 'mean_bb' => '14.0', 'std_dev' => '2.2', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '38', 'jk' => 'p', 'mean_bb' => '14.2', 'std_dev' => '2.25', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '39', 'jk' => 'p', 'mean_bb' => '14.4', 'std_dev' => '2.3', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '40', 'jk' => 'p', 'mean_bb' => '14.6', 'std_dev' => '2.3', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '41', 'jk' => 'p', 'mean_bb' => '14.8', 'std_dev' => '2.35', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '42', 'jk' => 'p', 'mean_bb' => '15.0', 'std_dev' => '2.4', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '43', 'jk' => 'p', 'mean_bb' => '15.2', 'std_dev' => '2.45', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '44', 'jk' => 'p', 'mean_bb' => '15.3', 'std_dev' => '2.55', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '45', 'jk' => 'p', 'mean_bb' => '15.5', 'std_dev' => '2.6', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '46', 'jk' => 'p', 'mean_bb' => '15.7', 'std_dev' => '2.6', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '47', 'jk' => 'p', 'mean_bb' => '15.9', 'std_dev' => '2.65', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '48', 'jk' => 'p', 'mean_bb' => '16.1', 'std_dev' => '2.7', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '49', 'jk' => 'p', 'mean_bb' => '16.3', 'std_dev' => '2.75', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '50', 'jk' => 'p', 'mean_bb' => '16.4', 'std_dev' => '2.85', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '51', 'jk' => 'p', 'mean_bb' => '16.6', 'std_dev' => '2.9', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '52', 'jk' => 'p', 'mean_bb' => '16.8', 'std_dev' => '2.9', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '53', 'jk' => 'p', 'mean_bb' => '17.0', 'std_dev' => '2.95', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '54', 'jk' => 'p', 'mean_bb' => '17.2', 'std_dev' => '3.0', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '55', 'jk' => 'p', 'mean_bb' => '17.3', 'std_dev' => '3.1', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '56', 'jk' => 'p', 'mean_bb' => '17.5', 'std_dev' => '3.15', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '57', 'jk' => 'p', 'mean_bb' => '17.7', 'std_dev' => '3.2', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '58', 'jk' => 'p', 'mean_bb' => '17.9', 'std_dev' => '3.25', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '59', 'jk' => 'p', 'mean_bb' => '18.0', 'std_dev' => '3.3', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '60', 'jk' => 'p', 'mean_bb' => '18.2', 'std_dev' => '3.35', 'created_at' => now(), 'updated_at' => now()],
        ];
        DB::table('whobb')->insert($data);
    }
}
