<?php

namespace Database\Seeders;

use App\Models\WhoTB;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class whoTBSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('whotb')->insert([
            ['usia' => '0', 'jk' => 'l', 'mean_tb' => '49.9', 'std_dev' => '1.9', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '1', 'jk' => 'l', 'mean_tb' => '54.7', 'std_dev' => '1.95', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '2', 'jk' => 'l', 'mean_tb' => '58.4', 'std_dev' => '2.0', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '3', 'jk' => 'l', 'mean_tb' => '61.4', 'std_dev' => '2.05', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '4', 'jk' => 'l', 'mean_tb' => '63.9', 'std_dev' => '2.05', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '5', 'jk' => 'l', 'mean_tb' => '65.9', 'std_dev' => '2.1', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '6', 'jk' => 'l', 'mean_tb' => '67.6', 'std_dev' => '2.15', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '7', 'jk' => 'l', 'mean_tb' => '69.2', 'std_dev' => '2.15', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '8', 'jk' => 'l', 'mean_tb' => '70.6', 'std_dev' => '2.2', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '9', 'jk' => 'l', 'mean_tb' => '72.0', 'std_dev' => '2.25', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '10', 'jk' => 'l', 'mean_tb' => '73.3', 'std_dev' => '2.3', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '11', 'jk' => 'l', 'mean_tb' => '74.5', 'std_dev' => '2.35', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '12', 'jk' => 'l', 'mean_tb' => '75.7', 'std_dev' => '2.4', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '13', 'jk' => 'l', 'mean_tb' => '76.9', 'std_dev' => '2.45', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '14', 'jk' => 'l', 'mean_tb' => '78.0', 'std_dev' => '2.5', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '15', 'jk' => 'l', 'mean_tb' => '79.1', 'std_dev' => '2.55', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '16', 'jk' => 'l', 'mean_tb' => '80.2', 'std_dev' => '2.6', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '17', 'jk' => 'l', 'mean_tb' => '81.2', 'std_dev' => '2.65', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '18', 'jk' => 'l', 'mean_tb' => '82.3', 'std_dev' => '2.7', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '19', 'jk' => 'l', 'mean_tb' => '83.2', 'std_dev' => '2.8', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '20', 'jk' => 'l', 'mean_tb' => '84.2', 'std_dev' => '2.8', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '21', 'jk' => 'l', 'mean_tb' => '85.1', 'std_dev' => '2.9', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '22', 'jk' => 'l', 'mean_tb' => '86.0', 'std_dev' => '2.95', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '23', 'jk' => 'l', 'mean_tb' => '86.9', 'std_dev' => '3.0', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '24', 'jk' => 'l', 'mean_tb' => '87.8', 'std_dev' => '3.05', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '24', 'jk' => 'l', 'mean_tb' => '87.1', 'std_dev' => '3.05', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '25', 'jk' => 'l', 'mean_tb' => '88.0', 'std_dev' => '3.1', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '26', 'jk' => 'l', 'mean_tb' => '88.8', 'std_dev' => '3.2', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '27', 'jk' => 'l', 'mean_tb' => '89.6', 'std_dev' => '3.25', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '28', 'jk' => 'l', 'mean_tb' => '90.4', 'std_dev' => '3.3', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '29', 'jk' => 'l', 'mean_tb' => '91.2', 'std_dev' => '3.35', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '30', 'jk' => 'l', 'mean_tb' => '91.9', 'std_dev' => '3.4', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '31', 'jk' => 'l', 'mean_tb' => '92.7', 'std_dev' => '3.45', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '32', 'jk' => 'l', 'mean_tb' => '93.4', 'std_dev' => '3.5', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '33', 'jk' => 'l', 'mean_tb' => '94.1', 'std_dev' => '3.55', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '34', 'jk' => 'l', 'mean_tb' => '94.8', 'std_dev' => '3.6', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '35', 'jk' => 'l', 'mean_tb' => '95.4', 'std_dev' => '3.65', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '36', 'jk' => 'l', 'mean_tb' => '96.1', 'std_dev' => '3.7', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '37', 'jk' => 'l', 'mean_tb' => '96.7', 'std_dev' => '3.75', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '38', 'jk' => 'l', 'mean_tb' => '97.4', 'std_dev' => '3.8', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '39', 'jk' => 'l', 'mean_tb' => '98.0', 'std_dev' => '3.85', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '40', 'jk' => 'l', 'mean_tb' => '98.6', 'std_dev' => '3.9', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '41', 'jk' => 'l', 'mean_tb' => '99.2', 'std_dev' => '3.95', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '42', 'jk' => 'l', 'mean_tb' => '99.9', 'std_dev' => '3.95', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '43', 'jk' => 'l', 'mean_tb' => '100.4', 'std_dev' => '4.05', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '44', 'jk' => 'l', 'mean_tb' => '101.0', 'std_dev' => '4.05', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '45', 'jk' => 'l', 'mean_tb' => '101.6', 'std_dev' => '4.1', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '46', 'jk' => 'l', 'mean_tb' => '102.0', 'std_dev' => '4.1', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '47', 'jk' => 'l', 'mean_tb' => '102.8', 'std_dev' => '4.15', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '48', 'jk' => 'l', 'mean_tb' => '103.3', 'std_dev' => '4.2', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '49', 'jk' => 'l', 'mean_tb' => '103.9', 'std_dev' => '4.25', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '50', 'jk' => 'l', 'mean_tb' => '104.4', 'std_dev' => '4.3', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '51', 'jk' => 'l', 'mean_tb' => '105.0', 'std_dev' => '4.3', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '52', 'jk' => 'l', 'mean_tb' => '105.6', 'std_dev' => '4.3', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '53', 'jk' => 'l', 'mean_tb' => '106.1', 'std_dev' => '4.4', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '54', 'jk' => 'l', 'mean_tb' => '106.7', 'std_dev' => '4.4', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '55', 'jk' => 'l', 'mean_tb' => '107.2', 'std_dev' => '4.45', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '56', 'jk' => 'l', 'mean_tb' => '107.8', 'std_dev' => '4.45', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '57', 'jk' => 'l', 'mean_tb' => '108.3', 'std_dev' => '4.55', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '58', 'jk' => 'l', 'mean_tb' => '108.9', 'std_dev' => '4.55', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '59', 'jk' => 'l', 'mean_tb' => '109.4', 'std_dev' => '4.6', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '60', 'jk' => 'l', 'mean_tb' => '110.0', 'std_dev' => '4.6', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],

            ['usia' => '0', 'jk' => 'p', 'mean_tb' => '49.1', 'std_dev' => '1.9', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '1', 'jk' => 'p', 'mean_tb' => '53.7', 'std_dev' => '1.95', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '2', 'jk' => 'p', 'mean_tb' => '57.1', 'std_dev' => '2.0', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '3', 'jk' => 'p', 'mean_tb' => '59.8', 'std_dev' => '2.1', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '4', 'jk' => 'p', 'mean_tb' => '62.1', 'std_dev' => '2.15', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '5', 'jk' => 'p', 'mean_tb' => '64.0', 'std_dev' => '2.25', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '6', 'jk' => 'p', 'mean_tb' => '65.7', 'std_dev' => '2.3', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '7', 'jk' => 'p', 'mean_tb' => '67.3', 'std_dev' => '2.3', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '8', 'jk' => 'p', 'mean_tb' => '68.7', 'std_dev' => '2.4', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '9', 'jk' => 'p', 'mean_tb' => '70.1', 'std_dev' => '2.45', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '10', 'jk' => 'p', 'mean_tb' => '71.5', 'std_dev' => '2.45', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '11', 'jk' => 'p', 'mean_tb' => '72.8', 'std_dev' => '2.5', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '12', 'jk' => 'p', 'mean_tb' => '74.0', 'std_dev' => '2.6', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '13', 'jk' => 'p', 'mean_tb' => '75.2', 'std_dev' => '2.65', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '14', 'jk' => 'p', 'mean_tb' => '76.4', 'std_dev' => '2.65', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '15', 'jk' => 'p', 'mean_tb' => '77.5', 'std_dev' => '2.75', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '16', 'jk' => 'p', 'mean_tb' => '78.6', 'std_dev' => '2.8', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '17', 'jk' => 'p', 'mean_tb' => '79.7', 'std_dev' => '2.85', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '18', 'jk' => 'p', 'mean_tb' => '80.7', 'std_dev' => '2.9', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '19', 'jk' => 'p', 'mean_tb' => '87.1', 'std_dev' => '2.95', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '20', 'jk' => 'p', 'mean_tb' => '82.7', 'std_dev' => '3.0', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '21', 'jk' => 'p', 'mean_tb' => '83.7', 'std_dev' => '3.05', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '22', 'jk' => 'p', 'mean_tb' => '84.6', 'std_dev' => '3.1', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '23', 'jk' => 'p', 'mean_tb' => '85.5', 'std_dev' => '3.2', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '24', 'jk' => 'p', 'mean_tb' => '86.4', 'std_dev' => '3.25', 'posisi' => 'terlentang', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '24', 'jk' => 'p', 'mean_tb' => '85.7', 'std_dev' => '3.25', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '25', 'jk' => 'p', 'mean_tb' => '86.6', 'std_dev' => '3.25', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '26', 'jk' => 'p', 'mean_tb' => '87.4', 'std_dev' => '3.35', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '27', 'jk' => 'p', 'mean_tb' => '88.3', 'std_dev' => '3.35', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '28', 'jk' => 'p', 'mean_tb' => '89.1', 'std_dev' => '3.45', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '29', 'jk' => 'p', 'mean_tb' => '89.9', 'std_dev' => '3.5', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '30', 'jk' => 'p', 'mean_tb' => '90.7', 'std_dev' => '3.5', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '31', 'jk' => 'p', 'mean_tb' => '91.4', 'std_dev' => '3.6', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '32', 'jk' => 'p', 'mean_tb' => '92.2', 'std_dev' => '3.6', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '33', 'jk' => 'p', 'mean_tb' => '92.9', 'std_dev' => '3.7', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '34', 'jk' => 'p', 'mean_tb' => '93.6', 'std_dev' => '3.75', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '35', 'jk' => 'p', 'mean_tb' => '94.4', 'std_dev' => '3.75', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '36', 'jk' => 'p', 'mean_tb' => '95.1', 'std_dev' => '3.8', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '37', 'jk' => 'p', 'mean_tb' => '95.7', 'std_dev' => '3.85', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '38', 'jk' => 'p', 'mean_tb' => '96.4', 'std_dev' => '3.9', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '39', 'jk' => 'p', 'mean_tb' => '97.1', 'std_dev' => '3.95', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '40', 'jk' => 'p', 'mean_tb' => '97.7', 'std_dev' => '4.0', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '41', 'jk' => 'p', 'mean_tb' => '98.4', 'std_dev' => '4.0', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '42', 'jk' => 'p', 'mean_tb' => '99.0', 'std_dev' => '4.1', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '43', 'jk' => 'p', 'mean_tb' => '99.7', 'std_dev' => '4.1', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '44', 'jk' => 'p', 'mean_tb' => '100.3', 'std_dev' => '4.15', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '45', 'jk' => 'p', 'mean_tb' => '100.9', 'std_dev' => '4.2', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '46', 'jk' => 'p', 'mean_tb' => '101.5', 'std_dev' => '4.25', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '47', 'jk' => 'p', 'mean_tb' => '102.1', 'std_dev' => '4.3', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '48', 'jk' => 'p', 'mean_tb' => '102.7', 'std_dev' => '4.3', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '49', 'jk' => 'p', 'mean_tb' => '103.3', 'std_dev' => '4.35', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '50', 'jk' => 'p', 'mean_tb' => '103.9', 'std_dev' => '4.4', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '51', 'jk' => 'p', 'mean_tb' => '104.5', 'std_dev' => '4.4', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '52', 'jk' => 'p', 'mean_tb' => '105.0', 'std_dev' => '4.5', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '53', 'jk' => 'p', 'mean_tb' => '105.6', 'std_dev' => '4.5', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '54', 'jk' => 'p', 'mean_tb' => '106.2', 'std_dev' => '4.5', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '55', 'jk' => 'p', 'mean_tb' => '106.7', 'std_dev' => '4.6', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '56', 'jk' => 'p', 'mean_tb' => '107.3', 'std_dev' => '4.6', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '57', 'jk' => 'p', 'mean_tb' => '107.8', 'std_dev' => '4.65', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '58', 'jk' => 'p', 'mean_tb' => '108.4', 'std_dev' => '4.65', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '59', 'jk' => 'p', 'mean_tb' => '108.9', 'std_dev' => '4.7', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],
            ['usia' => '60', 'jk' => 'p', 'mean_tb' => '109.4', 'std_dev' => '4.75', 'posisi' => 'berdiri', 'created_at' => now(), 'updated_at' => now()],



        ]);
    }
}
